version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "week8-project3"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ntcwcth0rm5b"
s3_prefix = "week8-project3"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
image_repositories = []
