AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  week8-project3

Resources:
  Project3Group3DynamoDB: 
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - 
          AttributeName: "id"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "id"
          KeyType: "HASH"
          
      BillingMode: PROVISIONED
      ProvisionedThroughput: 
        ReadCapacityUnits: "1"
        WriteCapacityUnits: "1"
      TableName: "Project3Group3Table"
            
  CRUDGet:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: crudGet.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Policies:
        - AmazonDynamoDBFullAccess
      Events:
        MyResourcesLambdaScanDynamodb:
          Type: Api
          Properties:
            Path: /
            Method: get
